- name: Deprovison rds-apb to openshift
  hosts: localhost
  gather_facts: true
  connection: local
  vars:
    state: 'absent'
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: rds-apb-openshift
    playbook_debug: false
